### ISSUE TITLE
Compatibility problem with 7.1.5

### ISSUE THREAD

**Issue by kadlec-g** [HenriWahl/seafadm#4]
It seems links changed in seafile, because "seafadm show users" can't list anything with seafile-server-7.1.5.
Could you fix it and release a new version of seafadm?
Thanks!
Jozsef

**Comment by HenriWahl** [comment]
I can confirm this - will look for solution.

**Comment by HenriWahl** [comment]
Can you please check with latest commit https://github.com/HenriWahl/seafadm/commit/34896ed0155274b4efc5e8835ac657f875a5060f - I switched user access via JSON API.

This seems to be a good idea anyway in the future. If you find other problems with 7.1.5 let me know.

**Comment by kadlec-g** [comment]
Hi,

On Wed, 13 Jan 2021, Henri Wahl wrote:

> Can you please check with latest commit 34896ed - I switched user access 
> via JSON API.
> 
> This seems to be a good idea anyway in the future. If you find other
> problems with 7.1.5 let me know.

Now I can receive the list of the users, thanks! However, the "first page" 
is listed only, i.e 25 users. Per page handling is different using the 
JSON API?

Best regards,
Jozsef

**Comment by HenriWahl** [comment]
My testing server had less than 25 users :-)

Re-added per page item declaration - can you test it again?

**Comment by kadlec-g** [comment]
On Wed, 13 Jan 2021, Henri Wahl wrote:

> My testing server had less than 25 users :-)
> 
> Re-added per page item declaration - can you test it again?

Perfect, thank you! That was quick! :-)

Best regards,
Jozsef
