### ISSUE TITLE
Cannot change a user's password

### ISSUE THREAD

**Issue by darxridge** [HenriWahl/seafadm#6]
Hi, thank you for this great tool, which I am using for data migration!

Unfortunately, I have no success with the 'update  password' command (other commands work).

I do:

  $ seafadm -u <admin_user_email> -p <admin_user_pass> -U <server-url> update <user_email> <new_user_pass>

The command returns with no errors and no other output.

Expected behaviour: I can log into seafile with <user_email> / <new_user_pass>

Observed behaviour: I can log into seafile with <user_email> / <old_user_pass>, i.e. the password has not changed.

Seafile/seafadm version: I have this problem on both versions 5.0 and 7.1

Any help would be greatly appreciated.

Thank you!
Richard

**Comment by HenriWahl** [comment]
Hi @darxridge,

Could you try to call the API of your Server directly as described in the **Update User Info** section of https://download.seafile.com/published/web-api/v2.1-admin/accounts.md ?

**Comment by darxridge** [comment]
Thank you, that worked. Next time I'll read the docs more carefully.
Thank you!
